### ISSUE TITLE
Request to Check if Compatible

### ISSUE THREAD

**Issue by LionelColaso** [jefferyharrell/ManyJobs#65]
[] Can you add support for [Easy Upgrades (Continued)](https://steamcommunity.com/sharedfiles/filedetails/?id=2904429048) so that there is option to split jobs added by this mod in own job columns

[] Can you check if compatible with below mods since they adds own job column
- [Improve This](https://steamcommunity.com/sharedfiles/filedetails/?id=2785022023)
- [Capture Them](https://steamcommunity.com/sharedfiles/filedetails/?id=2582758172) 

[] Can you check if compatible with below Mech mods that add jobs or add patches for these

XML Patches
- [Tiered Mechs](https://steamcommunity.com/workshop/filedetails/?id=2884029577)
- [Lifter Plz Do More Jobs](https://steamcommunity.com/sharedfiles/filedetails/?id=2884057958)
- [Paramedics Slaughter](https://steamcommunity.com/sharedfiles/filedetails/?id=2904976120)
- [Paramedics Feed Prisoners](https://steamcommunity.com/sharedfiles/filedetails/?id=2904976042)
- [Fabricors.can.craft.subcore.patch](https://steamcommunity.com/sharedfiles/filedetails/?id=2891005569)
C# Mods
- [Allow Tunnelers To Drill](https://steamcommunity.com/sharedfiles/filedetails/?id=2882915775)
- [Fabricors can repair mechs](https://steamcommunity.com/sharedfiles/filedetails/?id=2886185474)

[] Can you check below mod just in case 
- [Everyone can Work](https://steamcommunity.com/sharedfiles/filedetails/?id=2916914206)
- [Capable Slaves](https://steamcommunity.com/sharedfiles/filedetails/?id=2870120550)
- [Recruit Slaves](https://steamcommunity.com/sharedfiles/filedetails/?id=2887124861)
- [[RH2] CPERS: Arrest Here!](https://steamcommunity.com/sharedfiles/filedetails/?id=2563157350)

Sorry if its too much to ask , if you do look into it take your own time no hurry 
thanks in advance

**Comment by jefferyharrell** [comment]
It's not too much to ask. I really appreciate this. Thanks!

**Comment by jefferyharrell** [comment]
### Already compatible
Easy Upgrades (Continued), Improve This, Capture Them, Capable Slaves, Recruit Slaves, [RH2] CPERS: Arrest Here!

### Redundant with my mod
Paramedics Feed Prisoners

### No plans to support
Lifter Plz Do More Jobs, Paramedics Slaughter, Fabricors.can.craft.subcore.patch, 

### Conflicts wih my mod
Everyone can Work: If you want to use them both, load Everyone Can Work after Many Jobs

### Patch will be required
Tiered Mechs; I'll add it to the to do list as a maybe, since I haven't had any other requests for it yet
